package modelo

// Categoria representa las categorías léxicas
type Categoria int

// Definición de las categorías
const (
	NO_RECONOCIDO Categoria = iota
	ENTERO
	DECIMAL
	IDENTIFICADOR
	PALABRA_RESERVADA
	CADENA_CARACTERES
	COMENTARIO_LINEA
	COMENTARIO_BLOQUE
	OPERADOR_ARITMETICO
	OPERADOR_RELACIONAL
	OPERADOR_LOGICO
	OPERADOR_INCREMENTO
	NUMERO_NATURAL
	NUMERO_REAL
	OPERADOR_ASIGNACION
	PARENTESIS_APERTURA
	PARENTESIS_CIERRE
	LLAVE_APERTURA
	LLAVE_CIERRE
	TERMINAL
	SEPARADOR
	HEXADECIMAL
)
